// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5b0iWxJD8zvn9iz2XY-1PV8p_Yj3eZ9k',
    appId: '1:519094364706:web:0fee8afa596923f7d7b87b',
    messagingSenderId: '519094364706',
    projectId: 'kaskita-f65a6',
    authDomain: 'kaskita-f65a6.firebaseapp.com',
    storageBucket: 'kaskita-f65a6.firebasestorage.app',
    measurementId: 'G-R0MZP3Z7YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAig61A3QZWE4wdhbKIQ_Kh5wJTQUq20C4',
    appId: '1:519094364706:android:de6b31b1cc03bab6d7b87b',
    messagingSenderId: '519094364706',
    projectId: 'kaskita-f65a6',
    storageBucket: 'kaskita-f65a6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5b0iWxJD8zvn9iz2XY-1PV8p_Yj3eZ9k',
    appId: '1:519094364706:web:fad63c56b4b81fbfd7b87b',
    messagingSenderId: '519094364706',
    projectId: 'kaskita-f65a6',
    authDomain: 'kaskita-f65a6.firebaseapp.com',
    storageBucket: 'kaskita-f65a6.firebasestorage.app',
    measurementId: 'G-GXSWC2M069',
  );
}
